In [1]:
import tensorflow as tf
import os
os.environ["CUDA_DEVICE_ORDER"]="PCI_BUS_ID" # see issue #152
os.environ["CUDA_VISIBLE_DEVICES"]="0" # Will use only 2nd, 3rd and 4th gpu

In [2]:
# Rank 0 variables
mammal = tf.Variable("Elephant", tf.string)
ignition = tf.Variable(451, tf.int16)
floating = tf.Variable(3.141, tf.float64)
its_coomplicated = tf.Variable((12.3, -4.85), tf.complex64)

In [3]:
# Rank 1 vectors
mystr = tf.Variable(["Hello"], tf.string)
cool_numbers  = tf.Variable([3.14159, 2.71828], tf.float32)
first_primes = tf.Variable([2, 3, 5, 7, 11], tf.int32)
its_very_complicated = tf.Variable([(12.3, -4.85), (7.5, -6.23)], tf.complex64)

In [4]:
# Rank 2 Matrices
mymat = tf.Variable([[7],[11]], tf.int16)
myxor = tf.Variable([[False, True],[True, False]], tf.bool)
linear_squares = tf.Variable([[4], [9], [16], [25]], tf.int32)
squarish_squares = tf.Variable([ [4, 9], [16, 25] ], tf.int32)
mymatC = tf.Variable([[7],[11]], tf.int32)

In [5]:
#Launch the model in an interactive session
sess = tf.Session( )

#Initialise the created variables
tf.global_variables_initializer( ).run( session = sess )

print( sess.run( tf.rank(mymat) ) )

2


In [6]:
#Reshaping tensors
rank_three_tensor = tf.ones([3, 4, 5])

matrixA = tf.reshape(rank_three_tensor, [6, 10]) # Reshape existing content into a 6x10 matrix
matrixB = tf.reshape(rank_three_tensor, [3, -1]) # Reshape existing content into a 3x20 matrix. -1 tells reshape to calculate the size of this dimension
matricC = tf.reshape(matrixB, [4, 3, -1]) #Reshape existing content into a 4x3x5 tensor

In [7]:
#Data type casting
float_tensor = tf.cast(tf.constant([1, 2, 3]), dtype = tf.float32)

print(float_tensor.dtype)

<dtype: 'float32'>


In [19]:
#Evaluating Tensors
constant = tf.constant([1, 2, 3])
tensor = constant * constant
print( tensor.eval( session = sess ) )

print(tensor)
print(sess.run(tensor))
print(sess.run(tf.Print(tensor, [tensor])))

[1 4 9]
Tensor("mul_8:0", shape=(3,), dtype=int32)
[1 4 9]
[1 4 9]
